version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "127.0.0.1:27017:27017"  # Port mapping to localhost
    volumes:
      - mongodb-data:/data/db  # Mount a local directory into the container
    logging:
      driver: none

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "127.0.0.1:6379:6379"  # Port mapping to localhost
    logging:
      driver: none

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: reactjs-container
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-app
    environment:
      - NODE_ENV=development

  nodejs-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs-api-container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    # command: ["pm2-runtime", "start", "npm", "--", "start"]
    command: ["npm", "start"]

